const fs=require('fs'),path=require('path');
const root='C:/Users/andre/Desktop/Nearr-worktrees/nearr-1.6-fieldnotes';
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const write=(p,s)=>fs.writeFileSync(path.join(root,p),s);
let s=read('components/CandidatePhotoCarousel.tsx');
s=s.replace("import { Spacing } from '@/constants';", "import { Spacing } from '@/constants';\nimport { useTheme } from '@/lib/theme';");
s=s.replace(/const COLORS = \{[\s\S]*?\};\n/, '');
s=s.replace("  const { width: windowWidth } = useWindowDimensions();", "  const { colors } = useTheme();\n  const COLORS = { orange: colors.primary, cream: '#F7F4EE', muted: colors.textSecondary, surface: colors.surfaceElevated, border: colors.border };\n  const styles = useMemo(() => createStyles(COLORS), [colors]);\n  const { width: windowWidth } = useWindowDimensions();");
s=s.replace('const styles = StyleSheet.create({', "function createStyles(COLORS: { orange: string; cream: string; muted: string; surface: string; border: string }) { return StyleSheet.create({");
s=s.replace(/\}\);\s*$/, '}); }\n');
s=s.replace("  const rolodexItems = useMemo", "  const provenanceLabel = items[activeIndex]?.kind === 'places' ? 'Destination photo' : items[activeIndex]?.kind === 'source' || items[activeIndex]?.kind === 'frame' ? 'From your video' : null;\n  const rolodexItems = useMemo");
s=s.replace('    accessibilityLabel: `${accessibilityLabel}, photo ${index + 1} of ${items.length}`,', "    accessibilityLabel: `${item.kind === 'places' ? 'Destination photo' : 'From your video'}. ${accessibilityLabel}, photo ${index + 1} of ${items.length}`,\n    footerLabel: item.kind === 'places' ? 'Destination photo' : 'From your video',");
s=s.replace('            <View style={styles.expandBadge} pointerEvents="none">', '            <View style={styles.provenanceBadge} pointerEvents="none"><Text style={styles.provenanceText}>{first.kind === \'places\' ? \'Place photo\' : \'From video\'}</Text></View>\n            <View style={styles.expandBadge} pointerEvents="none">');
s=s.replace('          {items.length > 1 ? (', '          {provenanceLabel ? <View style={styles.provenanceBadge} pointerEvents="none"><Text style={styles.provenanceText}>{provenanceLabel}</Text></View> : null}\n          {items.length > 1 ? (');
s=s.replace('  root: {', "  provenanceBadge: { position: 'absolute', left: 8, top: 8, maxWidth: '80%', backgroundColor: 'rgba(23,26,24,0.88)', borderRadius: 8, paddingHorizontal: 7, paddingVertical: 4 },\n  provenanceText: { color: '#F7F4EE', fontSize: 11, lineHeight: 15, fontWeight: '600' },\n  root: {");
s=s.replace("position: 'absolute', right: 7, top: 7", "position: 'absolute', right: 7, bottom: 7");
write('components/CandidatePhotoCarousel.tsx',s);
s=read('components/SourceEvidenceGallery.tsx');
s=s.replace("import { Radius, Spacing } from '@/constants';", "import { Radius, Spacing } from '@/constants';\nimport { useTheme } from '@/lib/theme';");
s=s.replace(/const COLORS = \{[\s\S]*?\};\n/, '');
s=s.replace('  preview?: boolean;', '  preview?: boolean;\n  paired?: boolean;');
s=s.replace("title = 'Frames checked',", "title = 'From your video',").replace("subtitle = 'Evidence from the video',", "subtitle = 'Original post evidence',");
s=s.replace('  preview = false,', '  preview = false,\n  paired = false,');
s=s.replace('  const { width: windowWidth } = useWindowDimensions();', "  const { colors } = useTheme();\n  const COLORS = { cream: colors.text, orange: colors.accent, surface: colors.surfaceElevated, border: colors.border, muted: colors.textSecondary, black: colors.surfaceElevated };\n  const styles = useMemo(() => createStyles(COLORS), [colors]);\n  const { width: windowWidth, fontScale } = useWindowDimensions();\n  const [measuredWidth, setMeasuredWidth] = useState(0);\n  const stacked = windowWidth < 360 || fontScale > 1.25;");
s=s.replace('  const frameWidth = preview', '  const frameWidth = paired\n    ? measuredWidth || (stacked ? windowWidth - 48 : (windowWidth - 56) / 2)\n    : preview');
s=s.replace('  const frameHeight = preview ? 92', '  const frameHeight = paired ? (stacked ? 220 : 168) : preview ? 92');
s=s.replace('preview && styles.sectionPreview]} testID=', 'preview && styles.sectionPreview, paired && styles.sectionPaired]} onLayout={(event) => paired && setMeasuredWidth(Math.round(event.nativeEvent.layout.width))} testID=');
s=s.replaceAll('{!preview ?', '{!preview && !paired ?');
s=s.replace('          <Text style={styles.missingText}>Loading analyzed frames…</Text>', '          <Text style={styles.missingText}>Loading video frames…</Text>');
s=s.replace('Analyzed frames weren’t retained for this result.', 'Video frames are unavailable. You can still watch the original post.');
s=s.replace('                <View style={styles.timestampBadge}>', '                {paired ? <View style={styles.provenanceBadge}><Text style={styles.provenanceText}>From your video</Text></View> : null}\n                <View style={styles.timestampBadge}>');
s=s.replace('color={COLORS.cream}', 'color="#F7F4EE"');
s=s.replace('const styles = StyleSheet.create({', "function createStyles(COLORS: { cream: string; orange: string; surface: string; border: string; muted: string; black: string }) { return StyleSheet.create({");
s=s.replace(/\}\);\s*$/, '}); }\n');
s=s.replace('  section: {', "  sectionPaired: { marginTop: 0, marginBottom: 0, alignSelf: 'stretch' },\n  provenanceBadge: { position: 'absolute', left: 8, top: 8, backgroundColor: 'rgba(23,26,24,0.88)', borderRadius: 8, paddingHorizontal: 7, paddingVertical: 4 },\n  provenanceText: { color: '#F7F4EE', fontSize: 11, lineHeight: 15, fontWeight: '600' },\n  section: {");
s=s.replace('timestamp: { color: COLORS.cream', "timestamp: { color: '#F7F4EE'");
s=s.replace("right: Spacing.sm, top: Spacing.sm", "right: Spacing.sm, bottom: Spacing.sm");
write('components/SourceEvidenceGallery.tsx',s);
s=read('components/VayrinPresentationHeader.tsx');
s=s.replace('<View style={styles.orangeRule} />','');
s=s.replace('<Text style={styles.eyebrow}>NEARR</Text>', '<Text style={styles.eyebrow}>{looking ? \'FINDING A PLACE\' : \'FROM YOUR POST\'}</Text>');
s=s.replace('      padding: Spacing.lg,','      paddingVertical: Spacing.md,');
s=s.replace('      borderRadius: Radius.lg,','').replace('      backgroundColor: colors.surfaceElevated,','').replace('      borderWidth: StyleSheet.hairlineWidth,','').replace('      borderColor: colors.accentBorder,','');
s=s.replace('compact: { padding: Spacing.md,', 'compact: { paddingVertical: Spacing.sm,');
s=s.replace(/    orangeRule:.*\n/,'').replace('eyebrow: { color: colors.primary','eyebrow: { color: colors.textSecondary');
write('components/VayrinPresentationHeader.tsx',s);
s=read('components/ShareJobsHeader.tsx');
s=s.replace('styles.title]} numberOfLines={1}', 'styles.title]}');
s=s.replace('typography.title, styles.title','typography.heading, styles.title');
s=s.replace('your help','your check');
write('components/ShareJobsHeader.tsx',s);
s=read('components/ShareJobsSheet.tsx');
s=s.replace("Pressable, StyleSheet, View", "Pressable, StyleSheet, View, useWindowDimensions");
s=s.replace('  const { colors } = useTheme();','  const { colors } = useTheme();\n  const { fontScale, height } = useWindowDimensions();\n  const expandedForAccess = fontScale > 1.25 || height < 700;');
s=s.replace('        style={[\n          styles.sheet,','        style={[\n          styles.sheet,');
s=s.replace('              : styles.queueSheet,','              : styles.queueSheet,\n          expandedForAccess && styles.detailSheet,');
s=s.replace('        <View style={styles.dragIndicator} />','');
s=s.replace('borderTopLeftRadius: 24','borderTopLeftRadius: 28').replace('borderTopRightRadius: 24','borderTopRightRadius: 28');
s=s.replace("queueSheet: { height: '76%' }", "queueSheet: { height: '92%' }");
write('components/ShareJobsSheet.tsx',s);
