import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

type GoldRow = {
  actual_candidate_place_id?: string;
  actual_decision?: string;
  place_pass?: boolean;
  safe_to_auto_save?: string | boolean;
  failure_type?: string;
  url?: string;
};

function truthy(value: unknown): boolean {
  return value === true || value === 'true';
}

async function main(): Promise<void> {
  const root = path.resolve(__dirname, '..');
  const inputPath = path.join(root, 'artifacts', 'share-gold-results.json');
  const outputPath = path.join(root, 'artifacts', 'media-autosave-calibration.md');
  const rows = JSON.parse(await readFile(inputPath, 'utf8')) as GoldRow[];
  const correct = rows.filter((row) => row.place_pass === true).length;
  const incorrect = rows.filter((row) => !!row.actual_candidate_place_id && row.place_pass !== true).length;
  const ambiguous = rows.filter((row) => /picker|multi|ambiguous/i.test(row.actual_decision ?? '')).length;
  const unmatched = rows.filter((row) => !row.actual_candidate_place_id).length;
  const wrongLocation = rows.filter((row) => /wrong_country|wrong_location|wrong_branch/i.test(row.failure_type ?? '')).length;
  const eligible = rows.filter((row) => truthy(row.safe_to_auto_save)).length;
  const eligibleCorrect = rows.filter((row) => truthy(row.safe_to_auto_save) && row.place_pass === true).length;
  const eligibleIncorrect = rows.filter((row) => truthy(row.safe_to_auto_save) && row.place_pass !== true).length;
  const duplicateRows = rows.length - new Set(rows.map((row) => row.url).filter(Boolean)).size;
  const candidatePrecision = correct + incorrect > 0 ? correct / (correct + incorrect) : null;
  const autoSavePrecision = eligible > 0 ? eligibleCorrect / eligible : null;

  const report = `# Media Auto-Save Calibration\n\n` +
    `Generated by: \`npm run eval:media-autosave\`\n\n` +
    `## Approved Dataset\n\n` +
    `- Labeled post-level rows: ${rows.length}\n` +
    `- Correct verified candidate: ${correct}\n` +
    `- Incorrect verified candidate: ${incorrect}\n` +
    `- Ambiguous/picker outcomes: ${ambiguous}\n` +
    `- Unmatched outcomes: ${unmatched}\n` +
    `- Wrong location/branch labels: ${wrongLocation}\n` +
    `- Duplicate fixture rows: ${duplicateRows}\n` +
    `- Candidate precision among rows with a candidate: ${candidatePrecision === null ? 'not available' : `${(candidatePrecision * 100).toFixed(1)}%`}\n\n` +
    `## Auto-Save Gate\n\n` +
    `- Auto-save eligible in stored artifact: ${eligible}\n` +
    `- Auto-save correct: ${eligibleCorrect}\n` +
    `- Auto-save incorrect: ${eligibleIncorrect}\n` +
    `- Auto-save precision: ${autoSavePrecision === null ? 'not demonstrated (zero labeled eligible results)' : `${(autoSavePrecision * 100).toFixed(1)}%`}\n` +
    `- Host-only false auto-save: not measurable (host relationship is not labeled in this artifact)\n` +
    `- Duplicate insertion rate: measured separately by \`scripts/testShareJobPlaceResults.sql\` (expected 0%)\n` +
    `- Cross-user errors: measured separately by RLS/ownership SQL tests (expected 0)\n\n` +
    `## Rollout Decision\n\n` +
    `The stored gold artifact predates per-place Phase 2 gate diagnostics and cannot demonstrate the required 98% auto-save precision. The initial 0.92 deterministic score threshold is therefore an intentionally conservative canary policy, not a statistically calibrated global threshold. Keep automatic saving restricted to one authenticated canary user until labeled canary outcomes provide a non-zero denominator and at least 98% precision.\n`;

  await writeFile(outputPath, report, 'utf8');
  console.log(`Wrote ${path.relative(root, outputPath)}`);
  console.log(`rows=${rows.length} correct=${correct} incorrect=${incorrect} autosave_eligible=${eligible}`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});