import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { performance } from 'node:perf_hooks';
import { fieldnotesPhotoMarkerIds } from '../lib/fieldnotesMapPresentation';
import { savedMarkerPresentation } from '../lib/mapMarkerPresentation';
import { searchSavedPlaces } from '../lib/savedPlacesBrowse';
import type { SavedPlaceWithPlace } from '../types';

const read = (name: string) => readFileSync(name, 'utf8');
const fixture = (index: number): SavedPlaceWithPlace => ({ id: `saved-${index}`, user_id: 'owner', notes: index === 0 ? 'A quiet afternoon by the harbour' : null, ai_note: null, created_at: `2026-10-${String(index % 28 + 1).padStart(2, '0')}`, source_type: 'manual', source_url: null, category: 'beach', place: { id: `place-${index}`, name: index === 0 ? 'A very long destination name with several words and a coastline' : `Beach ${index}`, formatted_address: 'Hydra, Greece', category: 'beach', google_place_id: `provider-${index}`, latitude: 37.3, longitude: 23.4 } } as SavedPlaceWithPlace);
for (const count of [0, 1, 5, 20, 100, 1000]) {
  const places = Array.from({ length: count }, (_, index) => fixture(index));
  const selectedId = count ? places[0].id : null;
  const start = performance.now();
  const photos = fieldnotesPhotoMarkerIds(places, selectedId, 'local');
  assert.ok(photos.size <= 3, `${count} saves stay within the thumbnail budget`);
  assert.equal(photos.size, Math.min(3, count));
  if (selectedId) assert.ok(photos.has(selectedId), 'selection always survives the bounded allocation');
  assert.ok(places.every(place => place.id.startsWith('saved-')), 'allocation never mutates or drops the canonical dataset');
  assert.equal(fieldnotesPhotoMarkerIds(places, selectedId, 'dense').size, count ? 1 : 0);
  assert.equal(fieldnotesPhotoMarkerIds(places, selectedId, 'compact').size, count ? 1 : 0);
  console.log(`Fieldnotes ${count} saves: ${photos.size} photo slots, ${(performance.now() - start).toFixed(3)}ms desktop JS policy`);
}
const saved = fixture(0);
assert.equal(savedMarkerPresentation(saved, { selected: false, photoEligible: true, detailLevel: 'local', photoUri: 'file://known.jpg' }).visual, 'photo');
assert.equal(savedMarkerPresentation(saved, { selected: false, photoEligible: false, detailLevel: 'local', photoUri: 'file://known.jpg' }).visual, 'category');
assert.equal(savedMarkerPresentation(saved, { selected: false, photoEligible: true, detailLevel: 'dense', photoUri: 'file://known.jpg' }).visual, 'category');
assert.equal(savedMarkerPresentation(saved, { selected: true, detailLevel: 'local', photoUri: 'file://missing.jpg', photoFailed: true }).visual, 'category');
assert.equal(searchSavedPlaces([saved], 'harbour').length, 1, 'user notes are searchable without a provider');
assert.equal(searchSavedPlaces([saved], 'Hydra').length, 1, 'saved locality remains searchable offline');
const search = read('components/map/MapPlaceSearchDropdown.tsx');
assert.match(search, /if \(!visible \|\| offline \|\| scope !== 'new'\) return;/);
assert.match(search, /<FlatList<SearchRow>/, '100+ saves use a bounded list');
assert.match(search, /KeyboardAvoidingView/);
assert.match(search, /onSelectSaved\?\.\(saved\) : onPickPlace\(candidate!\)/, 'saved opens and discovery saves stay distinct');
assert.match(search, /index === 0 \? 'active_manual_search' : index < 4 \? 'compact_known_only' : 'offscreen_manual_search'/, 'no unbounded Google hydration');
const map = read('app/(tabs)/map.tsx');
assert.match(map, /<MapSavedDock saved=\{!selected && sheetSnap === 'full'\}/);
assert.match(map, /onSaved=\{\(\) => \{ if \(selected\) dismissSelectedPlace\(\); setSheetMode\('saved'\); setSheetOpenSignal/);
assert.match(map, /fontScale >= 1\.5\) setPreviewExpanded\(true\)/, 'large text gets the scrollable full destination surface');
const sheet = read('components/map/MapBottomSheet.tsx');
assert.match(sheet, /Account and Settings/);
assert.match(sheet, /<MemoizedSavedPlacesLibrary/);
assert.match(sheet, /if \(reducedMotion\) translateY\.setValue/);
const card = read('components/map/FieldnotesMapChrome.tsx');
assert.match(card, /place\.notes\?\.trim\(\) \|\| place\.ai_note\?\.trim\(\) \|\| null/);
assert.match(card, /accessibilityLabel=\{`Open \$\{place\.place\.name\} details`\}/);
assert.doesNotMatch(card, /getPlaceDetails|hydrateSavedPlace|fetch\(/);
console.log('PASS Fieldnotes map/search: bounded imagery, scale, saved/discovery separation, offline, keyboard, navigation, real reasons and accessible selection');
