-- Keep generated context separate from the user's explicit note.
-- Existing notes remain untouched and continue to be user-owned.
alter table public.saved_places
  add column if not exists ai_note text;

comment on column public.saved_places.ai_note is
  'Concise source-grounded context generated by Nearr; never overwrites notes.';
